# Generated by Django 5.0.2 on 2025-07-14 08:10

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Role',
                'verbose_name_plural': 'Roles',
                'db_table': 'roles',
            },
        ),
        migrations.CreateModel(
            name='AmountBox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('amount', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Amount Box',
                'verbose_name_plural': 'Amount Boxes',
                'db_table': 'amount_boxes',
                'indexes': [models.Index(fields=['name'], name='amount_boxe_name_5fea6d_idx'), models.Index(fields=['is_active'], name='amount_boxe_is_acti_5606da_idx')],
            },
        ),
        migrations.CreateModel(
            name='Box',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('amount', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount_box', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boxes', to='infrastructure.amountbox')),
            ],
            options={
                'verbose_name': 'Box',
                'verbose_name_plural': 'Boxes',
                'db_table': 'boxes',
            },
        ),
        migrations.CreateModel(
            name='BoxCleanUpEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('total_amount', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('box_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cleanup_events', to='infrastructure.box')),
            ],
            options={
                'verbose_name': 'Box Clean Up Event',
                'verbose_name_plural': 'Box Clean Up Events',
                'db_table': 'box_cleanup_events',
            },
        ),
        migrations.CreateModel(
            name='BoxCleanUpDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('box_cleanup_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='infrastructure.boxcleanupevent')),
            ],
            options={
                'verbose_name': 'Box Clean Up Detail',
                'verbose_name_plural': 'Box Clean Up Details',
                'db_table': 'box_cleanup_details',
            },
        ),
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('family_code', models.CharField(max_length=50, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Family',
                'verbose_name_plural': 'Families',
                'db_table': 'families',
                'indexes': [models.Index(fields=['name'], name='families_name_6cc707_idx'), models.Index(fields=['family_code'], name='families_family__3f5304_idx'), models.Index(fields=['is_active'], name='families_is_acti_78fc8b_idx')],
            },
        ),
        migrations.CreateModel(
            name='FamilyRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Family Role',
                'verbose_name_plural': 'Family Roles',
                'db_table': 'family_roles',
                'indexes': [models.Index(fields=['name'], name='family_role_name_27e293_idx')],
            },
        ),
        migrations.CreateModel(
            name='LoanState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=50, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Loan State',
                'verbose_name_plural': 'Loan States',
                'db_table': 'loan_states',
                'indexes': [models.Index(fields=['state'], name='loan_states_state_b9f323_idx')],
            },
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('title', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans', to='infrastructure.family')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans', to='infrastructure.loanstate')),
            ],
            options={
                'verbose_name': 'Loan',
                'verbose_name_plural': 'Loans',
                'db_table': 'loans',
            },
        ),
        migrations.CreateModel(
            name='TransactionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Transaction Type',
                'verbose_name_plural': 'Transaction Types',
                'db_table': 'transaction_types',
                'indexes': [models.Index(fields=['name'], name='transaction_name_16a261_idx')],
            },
        ),
        migrations.CreateModel(
            name='BoxTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('box', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='infrastructure.box')),
                ('transaction_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='box_transactions', to='infrastructure.transactiontype')),
            ],
            options={
                'verbose_name': 'Box Transaction',
                'verbose_name_plural': 'Box Transactions',
                'db_table': 'box_transactions',
            },
        ),
        migrations.CreateModel(
            name='AmountBoxTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount_box', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='infrastructure.amountbox')),
                ('transaction_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amount_box_transactions', to='infrastructure.transactiontype')),
            ],
            options={
                'verbose_name': 'Amount Box Transaction',
                'verbose_name_plural': 'Amount Box Transactions',
                'db_table': 'amount_box_transactions',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True, validators=[django.core.validators.EmailValidator()])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='infrastructure.role')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refresh_token', models.TextField()),
                ('client_uuid', models.CharField(max_length=255)),
                ('token_created_at', models.DateTimeField()),
                ('expires_at', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='infrastructure.user')),
            ],
            options={
                'verbose_name': 'Session',
                'verbose_name_plural': 'Sessions',
                'db_table': 'sessions',
            },
        ),
        migrations.CreateModel(
            name='SavingBox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saving_boxes', to='infrastructure.user')),
            ],
            options={
                'verbose_name': 'Saving Box',
                'verbose_name_plural': 'Saving Boxes',
                'db_table': 'saving_boxes',
            },
        ),
        migrations.CreateModel(
            name='PasswordReset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField(default=0)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_used', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='password_resets', to='infrastructure.user')),
            ],
            options={
                'verbose_name': 'Password Reset',
                'verbose_name_plural': 'Password Resets',
                'db_table': 'password_resets',
            },
        ),
        migrations.CreateModel(
            name='LoanRepayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('date', models.DateTimeField()),
                ('title', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repayments', to='infrastructure.loan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loan_repayments', to='infrastructure.user')),
            ],
            options={
                'verbose_name': 'Loan Repayment',
                'verbose_name_plural': 'Loan Repayments',
                'db_table': 'loan_repayments',
            },
        ),
        migrations.AddField(
            model_name='loan',
            name='from_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans_given', to='infrastructure.user'),
        ),
        migrations.AddField(
            model_name='loan',
            name='to_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans_received', to='infrastructure.user'),
        ),
        migrations.CreateModel(
            name='FamilyMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('is_banned', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='infrastructure.family')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='family_memberships', to='infrastructure.user')),
            ],
            options={
                'verbose_name': 'Family Member',
                'verbose_name_plural': 'Family Members',
                'db_table': 'family_members',
            },
        ),
        migrations.CreateModel(
            name='AmountBoxCleanUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('total_amount', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount_box_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cleanups', to='infrastructure.amountbox')),
            ],
            options={
                'verbose_name': 'Amount Box Clean Up',
                'verbose_name_plural': 'Amount Box Clean Ups',
                'db_table': 'amount_box_clean_ups',
                'indexes': [models.Index(fields=['amount_box_id'], name='amount_box__amount__6b13a2_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='box',
            index=models.Index(fields=['name'], name='boxes_name_89995c_idx'),
        ),
        migrations.AddIndex(
            model_name='box',
            index=models.Index(fields=['is_active'], name='boxes_is_acti_93a831_idx'),
        ),
        migrations.AddIndex(
            model_name='boxtransaction',
            index=models.Index(fields=['box'], name='box_transac_box_id_943980_idx'),
        ),
        migrations.AddIndex(
            model_name='boxtransaction',
            index=models.Index(fields=['transaction_type'], name='box_transac_transac_6d3006_idx'),
        ),
        migrations.AddIndex(
            model_name='amountboxtransaction',
            index=models.Index(fields=['amount_box'], name='amount_box__amount__b65fd8_idx'),
        ),
        migrations.AddIndex(
            model_name='amountboxtransaction',
            index=models.Index(fields=['transaction_type'], name='amount_box__transac_669d20_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['username'], name='users_usernam_baeb4b_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email'], name='users_email_4b85f2_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['role'], name='users_role_id_7a277c_idx'),
        ),
        migrations.AddIndex(
            model_name='session',
            index=models.Index(fields=['user'], name='sessions_user_id_7acd24_idx'),
        ),
        migrations.AddIndex(
            model_name='session',
            index=models.Index(fields=['refresh_token'], name='sessions_refresh_1ed06b_idx'),
        ),
        migrations.AddIndex(
            model_name='session',
            index=models.Index(fields=['client_uuid'], name='sessions_client__d7b951_idx'),
        ),
        migrations.AddIndex(
            model_name='session',
            index=models.Index(fields=['expires_at'], name='sessions_expires_bbb852_idx'),
        ),
        migrations.AddIndex(
            model_name='session',
            index=models.Index(fields=['is_active'], name='sessions_is_acti_b7284b_idx'),
        ),
        migrations.AddIndex(
            model_name='savingbox',
            index=models.Index(fields=['user'], name='saving_boxe_user_id_cccc90_idx'),
        ),
        migrations.AddIndex(
            model_name='passwordreset',
            index=models.Index(fields=['user'], name='password_re_user_id_a44016_idx'),
        ),
        migrations.AddIndex(
            model_name='passwordreset',
            index=models.Index(fields=['code'], name='password_re_code_ca5c43_idx'),
        ),
        migrations.AddIndex(
            model_name='passwordreset',
            index=models.Index(fields=['expires_at'], name='password_re_expires_d36310_idx'),
        ),
        migrations.AddIndex(
            model_name='passwordreset',
            index=models.Index(fields=['is_used'], name='password_re_is_used_f44bf3_idx'),
        ),
        migrations.AddIndex(
            model_name='loanrepayment',
            index=models.Index(fields=['loan'], name='loan_repaym_loan_id_6fa9cc_idx'),
        ),
        migrations.AddIndex(
            model_name='loanrepayment',
            index=models.Index(fields=['user'], name='loan_repaym_user_id_46df16_idx'),
        ),
        migrations.AddIndex(
            model_name='loanrepayment',
            index=models.Index(fields=['date'], name='loan_repaym_date_93f90b_idx'),
        ),
        migrations.AddIndex(
            model_name='loan',
            index=models.Index(fields=['family'], name='loans_family__68d9a6_idx'),
        ),
        migrations.AddIndex(
            model_name='loan',
            index=models.Index(fields=['from_user'], name='loans_from_us_fd9720_idx'),
        ),
        migrations.AddIndex(
            model_name='loan',
            index=models.Index(fields=['to_user'], name='loans_to_user_6a2511_idx'),
        ),
        migrations.AddIndex(
            model_name='loan',
            index=models.Index(fields=['state'], name='loans_state_i_3ecf13_idx'),
        ),
        migrations.AddIndex(
            model_name='loan',
            index=models.Index(fields=['created_at'], name='loans_created_99e948_idx'),
        ),
        migrations.AddIndex(
            model_name='familymember',
            index=models.Index(fields=['family'], name='family_memb_family__92fe93_idx'),
        ),
        migrations.AddIndex(
            model_name='familymember',
            index=models.Index(fields=['user'], name='family_memb_user_id_526aa9_idx'),
        ),
        migrations.AddIndex(
            model_name='familymember',
            index=models.Index(fields=['is_active'], name='family_memb_is_acti_91b18a_idx'),
        ),
        migrations.AddIndex(
            model_name='familymember',
            index=models.Index(fields=['is_banned'], name='family_memb_is_bann_d2c74b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='familymember',
            unique_together={('family', 'user')},
        ),
    ]
