# Generated by Django 5.0.2 on 2025-07-14 08:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CleanUpSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clean_up_day_interval', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clean_up_schedules', to='infrastructure.user')),
            ],
            options={
                'verbose_name': 'Clean Up Schedule',
                'verbose_name_plural': 'Clean Up Schedules',
                'db_table': 'clean_up_schedules',
                'indexes': [models.Index(fields=['user_id'], name='clean_up_sc_user_id_e2f744_idx')],
            },
        ),
    ]
