# Generated by Django 5.0.2 on 2025-07-14 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0002_cleanupschedule'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='amountboxcleanup',
            name='date',
        ),
        migrations.RemoveField(
            model_name='boxcleanupevent',
            name='date',
        ),
    ]
