# Generated by Django 5.0.2 on 2025-07-14 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0003_remove_amountboxcleanup_date_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='loanrepayment',
            name='loan_repaym_date_93f90b_idx',
        ),
        migrations.RemoveField(
            model_name='loanrepayment',
            name='date',
        ),
        migrations.AddField(
            model_name='loanrepayment',
            name='description',
            field=models.TextField(default='default'),
            preserve_default=False,
        ),
    ]
