# Generated by Django 5.0.2 on 2025-07-14 23:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0004_remove_loanrepayment_loan_repaym_date_93f90b_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='amountbox',
            name='user_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='amount_boxes', to='infrastructure.user'),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='amountbox',
            index=models.Index(fields=['user_id'], name='amount_boxe_user_id_70eefd_idx'),
        ),
    ]
