# Generated by Django 5.0.2 on 2025-07-14 23:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0005_amountbox_user_id_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='amountbox',
            name='amount_boxe_is_acti_5606da_idx',
        ),
        migrations.RemoveField(
            model_name='amountbox',
            name='is_active',
        ),
    ]
