# Generated by Django 5.0.2 on 2025-07-15 09:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0006_remove_amountbox_amount_boxe_is_acti_5606da_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavingBoxAmountBoxTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount_box', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saving_box_amount_box_transactions', to='infrastructure.amountbox')),
                ('saving_box', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amount_box_transactions', to='infrastructure.savingbox')),
                ('transaction_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saving_box_amount_box_transactions', to='infrastructure.transactiontype')),
            ],
            options={
                'verbose_name': 'Saving Box Amount Box Transaction',
                'verbose_name_plural': 'Saving Box Amount Box Transactions',
                'db_table': 'saving_box_amount_box_transactions',
                'indexes': [models.Index(fields=['saving_box'], name='saving_box__saving__ab1af7_idx'), models.Index(fields=['amount_box'], name='saving_box__amount__75bfff_idx'), models.Index(fields=['transaction_type'], name='saving_box__transac_5619ca_idx')],
            },
        ),
        migrations.CreateModel(
            name='SavingBoxBoxTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('box', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saving_box_box_transactions', to='infrastructure.box')),
                ('saving_box', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='box_transactions', to='infrastructure.savingbox')),
            ],
            options={
                'verbose_name': 'Saving Box Box Transaction',
                'verbose_name_plural': 'Saving Box Box Transactions',
                'db_table': 'saving_box_box_transactions',
                'indexes': [models.Index(fields=['saving_box'], name='saving_box__saving__5fcf9f_idx'), models.Index(fields=['box'], name='saving_box__box_id_1d3401_idx')],
            },
        ),
    ]
