# Generated by Django 5.0.2 on 2025-07-15 16:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0007_savingboxamountboxtransaction_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='savingboxboxtransaction',
            name='transaction_type',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='saving_box_box_transactions', to='infrastructure.transactiontype'),
            preserve_default=False,
        ),
    ]
