# Generated by Django 5.0.2 on 2025-07-16 09:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0008_savingboxboxtransaction_transaction_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boxcleanupevent',
            name='box_id',
        ),
        migrations.AddField(
            model_name='amountboxcleanup',
            name='box_cleanup_event_id',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, related_name='amount_box_clean_ups', to='infrastructure.boxcleanupevent'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='boxcleanupdetail',
            name='box_id',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, related_name='cleanup_details', to='infrastructure.box'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='boxcleanupevent',
            name='user_id',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, related_name='cleanup_events', to='infrastructure.user'),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='amountboxcleanup',
            index=models.Index(fields=['box_cleanup_event_id'], name='amount_box__box_cle_49d77c_idx'),
        ),
        migrations.AddIndex(
            model_name='boxcleanupdetail',
            index=models.Index(fields=['box_cleanup_event'], name='box_cleanup_box_cle_ff25d0_idx'),
        ),
        migrations.AddIndex(
            model_name='boxcleanupdetail',
            index=models.Index(fields=['box_id'], name='box_cleanup_box_id__93b9d0_idx'),
        ),
        migrations.AddIndex(
            model_name='boxcleanupevent',
            index=models.Index(fields=['user_id'], name='box_cleanup_user_id_3a8da0_idx'),
        ),
    ]
