# Generated by Django 5.0.2 on 2025-07-16 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0009_remove_boxcleanupevent_box_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amountboxcleanup',
            name='created_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='amountboxtransaction',
            name='created_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='boxcleanupdetail',
            name='created_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='boxcleanupevent',
            name='created_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='boxtransaction',
            name='created_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='passwordreset',
            name='created_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='savingboxamountboxtransaction',
            name='created_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='savingboxboxtransaction',
            name='created_at',
            field=models.DateTimeField(),
        ),
    ]
