# Generated by Django 5.0.2 on 2025-07-23 04:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0010_alter_amountboxcleanup_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanRepaymentState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=50, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Loan Repayment State',
                'verbose_name_plural': 'Loan Repayment States',
                'db_table': 'loan_repayment_states',
            },
        ),
        migrations.RenameField(
            model_name='amountbox',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='boxcleanupdetail',
            old_name='box_id',
            new_name='box',
        ),
        migrations.RenameField(
            model_name='boxcleanupevent',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='cleanupschedule',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameIndex(
            model_name='amountbox',
            new_name='amount_boxe_user_id_0ef9f9_idx',
            old_name='amount_boxe_user_id_70eefd_idx',
        ),
        migrations.RenameIndex(
            model_name='boxcleanupdetail',
            new_name='box_cleanup_box_id_99a91e_idx',
            old_name='box_cleanup_box_id__93b9d0_idx',
        ),
        migrations.RenameIndex(
            model_name='boxcleanupevent',
            new_name='box_cleanup_user_id_d9cab5_idx',
            old_name='box_cleanup_user_id_3a8da0_idx',
        ),
        migrations.RenameIndex(
            model_name='cleanupschedule',
            new_name='clean_up_sc_user_id_8972ab_idx',
            old_name='clean_up_sc_user_id_e2f744_idx',
        ),
        migrations.AddIndex(
            model_name='loanrepaymentstate',
            index=models.Index(fields=['state'], name='loan_repaym_state_6a1ebe_idx'),
        ),
        migrations.AddField(
            model_name='loanrepayment',
            name='loan_repayment_state',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, related_name='repayments', to='infrastructure.loanrepaymentstate'),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='loanrepayment',
            index=models.Index(fields=['loan_repayment_state'], name='loan_repaym_loan_re_41190e_idx'),
        ),
    ]
