# Generated by Django 5.0.2 on 2025-07-23 04:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0011_loanrepaymentstate_rename_user_id_amountbox_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='box',
            name='amount_box',
        ),
        migrations.AddField(
            model_name='box',
            name='user',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, related_name='boxes', to='infrastructure.user'),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='box',
            index=models.Index(fields=['user'], name='boxes_user_id_bf9046_idx'),
        ),
    ]
