# Generated by Django 5.0.2 on 2025-07-24 02:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0012_remove_box_amount_box_box_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amountboxtransaction',
            name='amount_box',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amount_box_transactions', to='infrastructure.amountbox'),
        ),
        migrations.CreateModel(
            name='AmountBoxBoxTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount_box', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amount_box_box_transactions', to='infrastructure.amountbox')),
                ('transaction_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amount_box_box_transactions', to='infrastructure.transactiontype')),
            ],
            options={
                'verbose_name': 'Amount Box Box Transaction',
                'verbose_name_plural': 'Amount Box Box Transactions',
                'db_table': 'amount_box_box_transactions',
            },
        ),
        migrations.DeleteModel(
            name='BoxTransaction',
        ),
        migrations.AddIndex(
            model_name='amountboxboxtransaction',
            index=models.Index(fields=['amount_box'], name='amount_box__amount__978ccd_idx'),
        ),
        migrations.AddIndex(
            model_name='amountboxboxtransaction',
            index=models.Index(fields=['transaction_type'], name='amount_box__transac_66fe3b_idx'),
        ),
    ]
