# Generated by Django 5.0.2 on 2025-07-24 17:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0013_alter_amountboxtransaction_amount_box_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoxTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('box', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='infrastructure.box')),
                ('transaction_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='box_transactions', to='infrastructure.transactiontype')),
            ],
            options={
                'verbose_name': 'Transacción de caja',
                'verbose_name_plural': 'Transacciones de cajas',
                'db_table': 'box_transactions',
                'ordering': ['-created_at'],
            },
        ),
    ]
